import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import Sidebar from "@/components/ui/Sidebar";
import Dashboard from "@/components/ui/Dashboard"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start justify-between`}>
      <Sidebar />
        <main className="grid w-full h-full pl-[300px]">          
        <div className="p-8">
          <Dashboard/>          
        </div>
        </main>
      </body>
    </html>
  );
}
