import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";

import { NewPath } from "@/components/NewPath";
import { PathCard } from "@/components/PathCard";
import { api } from "@/convex/_generated/api";
import { UserButton, useSession, useSignIn } from "@clerk/nextjs";
import { useQuery } from "convex/react";
import { useRouter } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

  
  const { signIn, isLoaded, setActive } = useSignIn();
  const router = useRouter();
  const paths = useQuery(api.paths.getPaths);

  if (!isLoaded) {
    return null;
  }

  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{

  return (
    <main className="flex flex-col">
      <div className="p-5 flex flex-col">
        <NewPath />
      </div>
      <div className="grid grid-cols-3 gap-5">
        {paths?.map((path) => <PathCard path={path} key={path._id} />)}
      </div>
    </main>
  );
}